slots:
  Project Maturity:
    Experimental: red
    Alpha: orange
    Beta: yellow
    Stable: green
    Legacy: orange
    Archived: red

  API Policy:
    Unstable: orange
    Mostly Stable: yellow
    SemVer: green
    Locked: yellow

  Maintenance Status:
    Active: green
    Supported: yellow
    Passive: orange
    Bugfix-Only: orange
    Sunset: red

  Intended Audience:
    Developers: blue
    Power Users: blue
    End Users: blue
    Ruby Developers: blue

repos:
  active_cabinet:  [Beta        , Mostly Stable, Bugfix-Only, Ruby Developers]
  alf:             [Stable      , Mostly Stable, Active     , Power Users    ]
  apicake:         [Beta        , Mostly Stable, Supported  , Ruby Developers]
  approvals:       [Stable      , Mostly Stable, Active     , Developers     ]
  arch-build:      [Beta        , Mostly Stable, Active     , Power Users    ]
  audio_addict:    [Stable      , Mostly Stable, Supported  , End Users      ]
  bashly:          [Stable      , SemVer       , Active     , Power Users    ]
  bobkit:          [Archived    , Locked       , Sunset     , Developers     ]
  completely:      [Stable      , Mostly Stable, Active     , Power Users    ]
  fuzzycd:         [Stable      , Mostly Stable, Active     , End Users      ]
  git-changelog:   [Stable      , Mostly Stable, Active     , Developers     ]
  gtx:             [Stable      , Mostly Stable, Active     , Ruby Developers]
  hash_cabinet:    [Beta        , Mostly Stable, Bugfix-Only, Ruby Developers]
  intrinio:        [Beta        , Mostly Stable, Passive    , End Users      ]
  jobly:           [Legacy      , Locked       , Sunset     , Developers     ]
  kojo:            [Stable      , Mostly Stable, Passive    , Power Users    ]
  madman:          [Legacy      , Unstable     , Sunset     , End Users      ]
  madness:         [Stable      , SemVer       , Supported  , End Users      ]
  mdview:          [Experimental, Unstable     , Active     , End Users      ]
  mister_bin:      [Stable      , Mostly Stable, Active     , Ruby Developers]
  mockly:          [Experimental, Unstable     , Active     , Developers     ]
  nlc:             [Experimental, Unstable     , Active     , End Users      ]
  opcode:          [Stable      , SemVer       , Active     , End Users      ]
  repli:           [Alpha       , Unstable     , Active     , Power Users    ]
  repocard:        [Experimental, Unstable     , Active     , Developers     ]
  respec:          [Stable      , Mostly Stable, Active     , Ruby Developers]
  rigit:           [Legacy      , Locked       , Sunset     , Power Users    ]
  rspec_approvals: [Stable      , Mostly Stable, Active     , Ruby Developers]
  runfile:         [Stable      , SemVer       , Active     , Ruby Developers]
  rush:            [Stable      , Mostly Stable, Active     , Power Users    ]
  rush-repo:       [Stable      , Locked       , Active     , Power Users    ]
  sam:             [Experimental, Unstable     , Active     , Power Users    ]
  secret_hub:      [Stable      , Mostly Stable, Passive    , Power Users    ]
  snapcrawl:       [Legacy      , Locked       , Sunset     , End Users      ]
  umagick:         [Alpha       , Unstable     , Supported  , Power Users    ]
  victor:          [Stable      , Mostly Stable, Active     , Ruby Developers]
  watchly:         [Alpha       , Unstable     , Active     , Ruby Developers]
  watchly-cli:     [Alpha       , Unstable     , Active     , End Users      ]

  # Unused yet
  colorly:         [Alpha       , Unstable     , Supported  , End Users      ]
  colsole:         [Stable      , SemVer       , Active     , Ruby Developers]
  concode:         [Stable      , Mostly Stable, Supported  , Ruby Developers]
  configly:        [Legacy      , Locked       , Sunset     , Ruby Developers]
  datamix:         [Alpha       , Unstable     , Supported  , Ruby Developers]
  docopt_ng:       [Stable      , Mostly Stable, Supported  , Ruby Developers]
  docspec:         [Alpha       , Unstable     , Passive    , Ruby Developers]
  dot_options:     [Beta        , Mostly Stable, Active     , Ruby Developers]
  enforce:         [Alpha       , Unstable     , Passive    , Power Users    ]
  eod:             [Alpha       , Unstable     , Passive    , End Users      ]
  erbx:            [Beta        , Mostly Stable, Passive    , Ruby Developers]
  extended_yaml:   [Beta        , Mostly Stable, Supported  , Ruby Developers]
  # fredric:
  # getcomments:
  # httpme:
  # icodi:
  # lightly:
  # loadrunner:
  # lp:
  # menu_commander:
  # minichart:
  # nasdaq:
  # pobject:
  # pretty_trace:
  # pundit_extra:
  # recode:
  # redirectly:
  # rentacop:
  # requires:
  # runfile-tasks:
  # sasstool:
  # sla:
  # slacktail:
  # slimview:
  # sting:
  # super_docopt:
