repos:
  active_cabinet:  [Beta        , Mostly Stable  , Bugfix-Only, Ruby Developers]
  alf:             [Stable      , Mostly Stable  , Active     , Power Users    ]
  apicake:         [Beta        , Mostly Stable  , Supported  , Ruby Developers]
  approvals:       [Stable      , Mostly Stable  , Active     , Developers     ]
  arch-build:      [Beta        , Mostly Stable  , Active     , Power Users    ]
  audio_addict:    [Stable      , Mostly Stable  , Supported  , End Users      ]
  bashly:          [Stable      , SemVer         , Active     , Power Users    ]
  bobkit:          [Archived    , Locked         , Sunset     , Developers     ]
  colorly:         [Alpha       , Unstable       , Supported  , End Users      ]
  colsole:         [Stable      , SemVer         , Active     , Ruby Developers]
  completely:      [Stable      , Mostly Stable  , Active     , Power Users    ]
  concode:         [Stable      , Mostly Stable  , Supported  , Ruby Developers]
  configly:        [Legacy      , Locked         , Sunset     , Ruby Developers]
  datamix:         [Alpha       , Unstable       , Supported  , Ruby Developers]
  docopt_ng:       [Stable      , Mostly Stable  , Supported  , Ruby Developers]
  docspec:         [Alpha       , Unstable       , Passive    , Ruby Developers]
  dot_options:     [Beta        , Mostly Stable  , Active     , Ruby Developers]
  enforce:         [Alpha       , Unstable       , Passive    , Power Users    ]
  eod:             [Alpha       , Unstable       , Passive    , End Users      ]
  erbx:            [Beta        , Mostly Stable  , Passive    , Ruby Developers]
  extended_yaml:   [Beta        , Mostly Stable  , Supported  , Ruby Developers]
  fredric:         [Alpha       , Unstable       , Supported  , End Users      ]
  fuzzycd:         [Stable      , Mostly Stable  , Active     , End Users      ]
  getcomments:     [Legacy      , Locked         , Sunset     , Ruby Developers]
  git-changelog:   [Stable      , Mostly Stable  , Active     , Developers     ]
  gtx:             [Stable      , Mostly Stable  , Active     , Ruby Developers]
  hash_cabinet:    [Beta        , Mostly Stable  , Bugfix-Only, Ruby Developers]
  httpme:          [Beta        , Mostly Stable  , Active     , End Users      ]
  icodi:           [Stable      , Mostly Stable  , Supported  , Ruby Developers]
  intrinio:        [Beta        , Mostly Stable  , Passive    , End Users      ]
  jobly:           [Legacy      , Locked         , Sunset     , Developers     ]
  kojo:            [Stable      , Mostly Stable  , Passive    , Power Users    ]
  lightly:         [Stable      , Mostly Stable  , Supported  , Ruby Developers]
  loadrunner:      [Alpha       , Unstable       , Passive    , Developers     ]
  lp:              [Stable      , Mostly Stable  , Active     , Ruby Developers]
  madman:          [Legacy      , Unstable       , Sunset     , End Users      ]
  madness:         [Stable      , SemVer         , Supported  , End Users      ]
  mdview:          [Experimental, Unstable       , Active     , End Users      ]
  menu_commander:  [Beta        , Mostly Stable  , Passive    , Power Users    ]
  minichart:       [Alpha       , Mostly Stable  , Supported  , Ruby Developers]
  mister_bin:      [Stable      , Mostly Stable  , Active     , Ruby Developers]
  mockly:          [Experimental, Highly Unstable, Active     , Developers     ]
  nasdaq:          [Alpha       , Mostly Stable  , Passive    , End Users      ]
  nlc:             [Experimental, Highly Unstable, Active     , End Users      ]
  opcode:          [Stable      , SemVer         , Active     , End Users      ]
  pobject:         [Beta        , Mostly Stable  , Passive    , Ruby Developers]
  pretty_trace:    [Stable      , Mostly Stable  , Active     , Ruby Developers]
  pundit_extra:    [Stable      , Mostly Stable  , Passive    , Ruby Developers]
  recode:          [Alpha       , Mostly Stable  , Passive    , Developers     ]
  redirectly:      [Beta        , Mostly Stable  , Passive    , Power Users    ]
  rentacop:        [Stable      , Mostly Stable  , Active     , Ruby Developers]
  repli:           [Alpha       , Unstable       , Active     , Power Users    ]
  repocard:        [Alpha       , Unstable       , Active     , Developers     ]
  requires:        [Stable      , SemVer         , Active     , Ruby Developers]
  respec:          [Stable      , Mostly Stable  , Active     , Ruby Developers]
  rigit:           [Legacy      , Locked         , Sunset     , Power Users    ]
  rspec_approvals: [Stable      , Mostly Stable  , Active     , Ruby Developers]
  runfile-tasks:   [Stable      , Unstable       , Active     , Ruby Developers]
  runfile:         [Stable      , SemVer         , Active     , Ruby Developers]
  rush-repo:       [Stable      , Locked         , Active     , Power Users    ]
  rush:            [Stable      , Mostly Stable  , Active     , Power Users    ]
  sam:             [Experimental, Unstable       , Active     , Power Users    ]
  sasstool:        [Stable      , Mostly Stable  , Supported  , Developers     ]
  secret_hub:      [Stable      , Mostly Stable  , Passive    , Power Users    ]
  sla:             [Beta        , Mostly Stable  , Supported  , Developers     ]
  slacktail:       [Legacy      , Locked         , Sunset     , Power Users    ]
  slimview:        [Beta        , Mostly Stable  , Active     , End Users      ]
  snapcrawl:       [Legacy      , Locked         , Sunset     , End Users      ]
  sting:           [Stable      , Mostly Stable  , Active     , Ruby Developers]
  super_docopt:    [Stable      , Mostly Stable  , Passive    , Ruby Developers]
  umagick:         [Alpha       , Unstable       , Supported  , Power Users    ]
  victor:          [Stable      , Mostly Stable  , Active     , Ruby Developers]
  victor-cli:      [Stable      , Mostly Stable  , Active     , Ruby Developers]
  watchly-cli:     [Alpha       , Unstable       , Active     , End Users      ]
  watchly:         [Alpha       , Unstable       , Active     , Ruby Developers]
  yo:              [Experimental, Highly Unstable, Active     , Power Users    ]

slots:
  Project Maturity:
    Experimental: red
    Alpha: orange
    Beta: yellow
    Stable: green
    Legacy: orange
    Archived: red

  API Policy:
    Highly Unstable: red
    Unstable: orange
    Mostly Stable: yellow
    SemVer: green
    Locked: yellow

  Maintenance Status:
    Active: green
    Supported: yellow
    Passive: orange
    Bugfix-Only: orange
    Sunset: red

  Intended Audience:
    Developers: blue
    Power Users: blue
    End Users: blue
    Ruby Developers: blue
