slots:
  Project Maturity:
    Experimental: red
    Alpha: orange
    Beta: yellow
    Stable: green
    Legacy: orange
    Archived: red

  API Policy:
    Unstable: orange
    Mostly Stable: yellow
    SemVer: green
    Locked: yellow

  Maintenance Status:
    Active: green
    Supported: yellow
    Passive: orange
    Bugfix-Only: orange
    Sunset: red

  Intended Audience:
    Developers: blue
    Power Users: blue
    End Users: blue
    Ruby Developers: blue

repos:
  active_cabinet:  [Beta        , Mostly Stable, Bugfix-Only, Ruby Developers]
  alf:             [Stable      , Mostly Stable, Active     , Power Users    ]
  apicake:         [Beta        , Mostly Stable, Supported  , Ruby Developers]
  approvals:       [Stable      , Mostly Stable, Active     , Developers     ]
  audio_addict:    [Stable      , Mostly Stable, Supported  , End Users      ]
  bashly:          [Stable      , SemVer       , Active     , Power Users    ]
  bobkit:          [Archived    , Locked       , Sunset     , Developers     ]
  completely:      [Stable      , Mostly Stable, Active     , Power Users    ]
  fuzzycd:         [Stable      , Mostly Stable, Active     , End Users      ]
  git-changelog:   [Stable      , Mostly Stable, Active     , Developers     ]
  gtx:             [Stable      , Mostly Stable, Active     , Ruby Developers]
  hash_cabinet:    [Beta        , Mostly Stable, Bugfix-Only, Ruby Developers]
  intrinio:        [Beta        , Mostly Stable, Passive    , End Users      ]
  jobly:           [Legacy      , Locked       , Sunset     , Developers     ]
  kojo:            [Stable      , Mostly Stable, Passive    , Power Users    ]
  madman:          [Legacy      , Unstable     , Sunset     , End Users      ]
  madness:         [Stable      , SemVer       , Supported  , End Users      ]
  mdview:          [Experimental, Unstable     , Active     , End Users      ]
  mister_bin:      [Stable      , Mostly Stable, Active     , Ruby Developers]
  mockly:          [Experimental, Unstable     , Active     , Developers     ]
  nlc:             [Experimental, Unstable     , Active     , End Users      ]
  opcode:          [Stable      , SemVer       , Active     , End Users      ]
  repli:           [Alpha       , Unstable     , Active     , Power Users    ]
  repocard:        [Experimental, Unstable     , Active     , Developers     ]
  respec:          [Stable      , Mostly Stable, Active     , Ruby Developers]
  rigit:           [Legacy      , Locked       , Sunset     , Power Users    ]
  rspec_approvals: [Stable      , Mostly Stable, Active     , Ruby Developers]
  runfile:         [Stable      , SemVer       , Active     , Ruby Developers]
  rush:            [Stable      , Mostly Stable, Active     , Power Users    ]
  rush-repo:       [Stable      , Locked       , Active     , Power Users    ]
  sam:             [Experimental, Unstable     , Active     , Power Users    ]
  secret_hub:      [Stable      , Mostly Stable, Passive    , Power Users    ]
  snapcrawl:       [Legacy      , Locked       , Sunset     , End Users      ]
  umagick:         [Alpha       , Unstable     , Supported  , Power Users    ]
  victor:          [Stable      , Mostly Stable, Active     , Ruby Developers]
  watchly:         [Alpha       , Unstable     , Active     , Ruby Developers]
  watchly-cli:     [Alpha       , Unstable     , Active     , End Users      ]
